name: Commit Stage
on: push

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
      security-events: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: 'maven'
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Package without test
        run: mvn clean package -DskipTests